[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
monitor_speed = 115200
monitor_port = /dev/tty.usbserial-1110

lib_deps = 
    exothink/eXoCAN@^1.0.0

build_flags = 
    -D HAL_CAN_MODULE_ENABLED

upload_protocol = serial
upload_port = /dev/tty.usbserial-1110
upload_speed = 115200